#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

function checkout() {
  repo=$1; url=$2; sha=$3

  if [ ! -d "$repo" ]; then
    git clone "https://github.com/$url" "$repo"
  fi

  pushd "$repo"
  git fetch && git reset --hard "$sha"
  popd
}

checkout examples/chatito rodrigopivi/chatito 8ad5d9835e1a0c7b95af7693cb58c0320ffc806f

known_failures="$(cat script/known_failures.txt)"

tree-sitter parse -q \
  'examples/**/*.chatito' \
  "$(for file in $known_failures; do echo "!${file}"; done)"

example_count=$(find examples -name '*.chatito' | wc -l)
failure_count=$(wc -w <<< "$known_failures")
success_count=$(( example_count - failure_count ))
success_percent=$(bc -l <<< "100*${success_count}/${example_count}")

printf \
  "Successfully parsed %d of %d example files (%.1f%%)\n" \
  $success_count "$example_count" "$success_percent"
