#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 156
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 2
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 9

enum {
  anon_sym_PERCENT_LBRACK = 1,
  aux_sym_intent_def_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_AT_LBRACK = 4,
  aux_sym_slot_def_token1 = 5,
  anon_sym_TILDE_LBRACK = 6,
  anon_sym_import = 7,
  anon_sym_PIPE = 8,
  aux_sym_import_token1 = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_QMARK = 11,
  aux_sym_word_token1 = 12,
  anon_sym_POUND = 13,
  anon_sym_STAR_LBRACK = 14,
  anon_sym_PERCENT = 15,
  sym_number = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  sym_eq = 20,
  anon_sym_DQUOTE = 21,
  aux_sym_string_token1 = 22,
  anon_sym_SQUOTE = 23,
  aux_sym_string_token2 = 24,
  sym_escape = 25,
  sym__eol = 26,
  sym__indent = 27,
  sym__space = 28,
  sym_source = 29,
  sym__definition = 30,
  sym_intent_def = 31,
  sym_slot_def = 32,
  sym_alias_def = 33,
  sym_import = 34,
  sym_comment = 35,
  sym_intent_body = 36,
  sym_slot_body = 37,
  sym_alias_body = 38,
  sym_slot_ref = 39,
  sym_alias_ref = 40,
  sym_word = 41,
  sym_variation = 42,
  sym_probability = 43,
  sym_arguments = 44,
  sym_argument = 45,
  sym_string = 46,
  aux_sym_source_repeat1 = 47,
  aux_sym_intent_body_repeat1 = 48,
  aux_sym_intent_body_repeat2 = 49,
  aux_sym_slot_body_repeat1 = 50,
  aux_sym_slot_body_repeat2 = 51,
  aux_sym_alias_body_repeat1 = 52,
  aux_sym_word_repeat1 = 53,
  aux_sym_arguments_repeat1 = 54,
  aux_sym_string_repeat1 = 55,
  aux_sym_string_repeat2 = 56,
  alias_sym_intent = 57,
  alias_sym_slot = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT_LBRACK] = "%[",
  [aux_sym_intent_def_token1] = "alias",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT_LBRACK] = "@[",
  [aux_sym_slot_def_token1] = "slot_def_token1",
  [anon_sym_TILDE_LBRACK] = "~[",
  [anon_sym_import] = "import",
  [anon_sym_PIPE] = "|",
  [aux_sym_import_token1] = "file",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_QMARK] = "\?",
  [aux_sym_word_token1] = "word_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR_LBRACK] = "*[",
  [anon_sym_PERCENT] = "%",
  [sym_number] = "number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_eq] = "eq",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_escape] = "escape",
  [sym__eol] = "_eol",
  [sym__indent] = "_indent",
  [sym__space] = "_space",
  [sym_source] = "source",
  [sym__definition] = "_definition",
  [sym_intent_def] = "intent_def",
  [sym_slot_def] = "slot_def",
  [sym_alias_def] = "alias_def",
  [sym_import] = "import",
  [sym_comment] = "comment",
  [sym_intent_body] = "intent_body",
  [sym_slot_body] = "slot_body",
  [sym_alias_body] = "alias_body",
  [sym_slot_ref] = "slot_ref",
  [sym_alias_ref] = "alias_ref",
  [sym_word] = "word",
  [sym_variation] = "variation",
  [sym_probability] = "probability",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_string] = "string",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_intent_body_repeat1] = "intent_body_repeat1",
  [aux_sym_intent_body_repeat2] = "intent_body_repeat2",
  [aux_sym_slot_body_repeat1] = "slot_body_repeat1",
  [aux_sym_slot_body_repeat2] = "slot_body_repeat2",
  [aux_sym_alias_body_repeat1] = "alias_body_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [alias_sym_intent] = "intent",
  [alias_sym_slot] = "slot",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT_LBRACK] = anon_sym_PERCENT_LBRACK,
  [aux_sym_intent_def_token1] = aux_sym_intent_def_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [aux_sym_slot_def_token1] = aux_sym_slot_def_token1,
  [anon_sym_TILDE_LBRACK] = anon_sym_TILDE_LBRACK,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR_LBRACK] = anon_sym_STAR_LBRACK,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_number] = sym_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_eq] = sym_eq,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_escape] = sym_escape,
  [sym__eol] = sym__eol,
  [sym__indent] = sym__indent,
  [sym__space] = sym__space,
  [sym_source] = sym_source,
  [sym__definition] = sym__definition,
  [sym_intent_def] = sym_intent_def,
  [sym_slot_def] = sym_slot_def,
  [sym_alias_def] = sym_alias_def,
  [sym_import] = sym_import,
  [sym_comment] = sym_comment,
  [sym_intent_body] = sym_intent_body,
  [sym_slot_body] = sym_slot_body,
  [sym_alias_body] = sym_alias_body,
  [sym_slot_ref] = sym_slot_ref,
  [sym_alias_ref] = sym_alias_ref,
  [sym_word] = sym_word,
  [sym_variation] = sym_variation,
  [sym_probability] = sym_probability,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym_string] = sym_string,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_intent_body_repeat1] = aux_sym_intent_body_repeat1,
  [aux_sym_intent_body_repeat2] = aux_sym_intent_body_repeat2,
  [aux_sym_slot_body_repeat1] = aux_sym_slot_body_repeat1,
  [aux_sym_slot_body_repeat2] = aux_sym_slot_body_repeat2,
  [aux_sym_alias_body_repeat1] = aux_sym_alias_body_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [alias_sym_intent] = alias_sym_intent,
  [alias_sym_slot] = alias_sym_slot,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_intent_def_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_slot_def_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_intent_def] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_def] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_def] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_intent_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_body] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_variation] = {
    .visible = true,
    .named = true,
  },
  [sym_probability] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_alias_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_intent] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_slot] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_content = 1,
  field_id = 2,
  field_key = 3,
  field_quote = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_key] = "key",
  [field_quote] = "quote",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 2},
  [5] = {.index = 3, .length = 3},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_quote, 0},
    {field_quote, 1},
  [3] =
    {field_content, 1},
    {field_quote, 0},
    {field_quote, 2},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_key, 0},
    {field_value, 3},
  [10] =
    {field_key, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = alias_sym_intent,
  },
  [3] = {
    [1] = alias_sym_slot,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 42,
  [61] = 61,
  [62] = 43,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 51,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 44,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 85,
  [97] = 82,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 108,
  [116] = 106,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 130,
  [153] = 132,
  [154] = 119,
  [155] = 144,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '\t') ADVANCE(55);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '?') ADVANCE(39);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '|') ADVANCE(35);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(61);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '?') ADVANCE(39);
      if (lookahead == ']') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == '~') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == '~') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '~') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '~') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(58);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 11:
      if (lookahead == '[') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == '[') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '\t') ADVANCE(62);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '0') ADVANCE(47);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '?') ADVANCE(39);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == '|') ADVANCE(35);
      if (lookahead == '~') ADVANCE(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_intent_def_token1);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_slot_def_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_TILDE_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_word_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(31);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(33);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_STAR_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(19);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'u') ADVANCE(23);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          ('t' <= lookahead && lookahead <= 'v')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == 'u') ADVANCE(23);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          ('t' <= lookahead && lookahead <= 'v')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__indent);
      if (lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 26},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 26},
  [7] = {.lex_state = 26},
  [8] = {.lex_state = 26},
  [9] = {.lex_state = 26},
  [10] = {.lex_state = 26},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 26},
  [16] = {.lex_state = 26},
  [17] = {.lex_state = 26},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 26},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 26},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 26},
  [24] = {.lex_state = 26},
  [25] = {.lex_state = 26},
  [26] = {.lex_state = 26},
  [27] = {.lex_state = 26},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 26},
  [30] = {.lex_state = 26},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 26},
  [33] = {.lex_state = 26},
  [34] = {.lex_state = 26},
  [35] = {.lex_state = 26},
  [36] = {.lex_state = 26},
  [37] = {.lex_state = 26},
  [38] = {.lex_state = 26},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 26},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 26},
  [47] = {.lex_state = 26},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 26},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 26},
  [53] = {.lex_state = 26},
  [54] = {.lex_state = 26},
  [55] = {.lex_state = 26},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 26},
  [58] = {.lex_state = 26},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 26},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 26},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 26},
  [80] = {.lex_state = 9},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 26},
  [84] = {.lex_state = 9},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 8},
  [91] = {.lex_state = 26},
  [92] = {.lex_state = 26},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 26},
  [95] = {.lex_state = 26},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 5},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 26},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 26},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 26},
  [108] = {.lex_state = 26},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 26},
  [112] = {.lex_state = 26},
  [113] = {.lex_state = 26},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 26},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 7},
  [118] = {.lex_state = 26},
  [119] = {.lex_state = 25},
  [120] = {.lex_state = 24},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 26},
  [124] = {.lex_state = 26},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 26},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 26},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 26},
  [133] = {.lex_state = 25},
  [134] = {.lex_state = 24},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 26},
  [138] = {.lex_state = 3},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 26},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 26},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 26},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 25},
  [147] = {.lex_state = 7},
  [148] = {.lex_state = 26},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 24},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 26},
  [153] = {.lex_state = 26},
  [154] = {.lex_state = 25},
  [155] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [aux_sym_word_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(139),
    [sym__definition] = STATE(3),
    [sym_intent_def] = STATE(37),
    [sym_slot_def] = STATE(37),
    [sym_alias_def] = STATE(37),
    [sym_import] = STATE(3),
    [sym_comment] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT_LBRACK] = ACTIONS(5),
    [anon_sym_AT_LBRACK] = ACTIONS(7),
    [anon_sym_TILDE_LBRACK] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [aux_sym_comment_token1] = ACTIONS(15),
    [sym__eol] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(24), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(27), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(30), 1,
      anon_sym_import,
    ACTIONS(33), 1,
      anon_sym_PIPE,
    ACTIONS(36), 1,
      aux_sym_comment_token1,
    ACTIONS(39), 1,
      sym__eol,
    STATE(37), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(2), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [36] = 10,
    ACTIONS(5), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(7), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(9), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      sym__eol,
    STATE(37), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(2), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [72] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(48), 1,
      sym__indent,
    STATE(10), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
    ACTIONS(46), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [92] = 8,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(56), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(58), 1,
      sym__space,
    STATE(18), 1,
      sym_probability,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(11), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [120] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(62), 1,
      sym__indent,
    STATE(8), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [140] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      sym__indent,
    STATE(9), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
    ACTIONS(64), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [160] = 4,
    ACTIONS(70), 1,
      aux_sym_comment_token1,
    ACTIONS(73), 1,
      sym__indent,
    STATE(8), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [180] = 4,
    ACTIONS(78), 1,
      aux_sym_comment_token1,
    ACTIONS(81), 1,
      sym__indent,
    STATE(9), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [200] = 4,
    ACTIONS(86), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      sym__indent,
    STATE(10), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      sym__eol,
  [220] = 7,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(92), 1,
      sym__eol,
    ACTIONS(94), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(12), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [245] = 7,
    ACTIONS(96), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(99), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(102), 1,
      aux_sym_word_token1,
    ACTIONS(105), 1,
      sym__eol,
    ACTIONS(107), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(12), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [270] = 7,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(94), 1,
      sym__space,
    ACTIONS(110), 1,
      sym__eol,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(12), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [295] = 7,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(94), 1,
      sym__space,
    ACTIONS(112), 1,
      sym__eol,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(12), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [320] = 1,
    ACTIONS(114), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [332] = 1,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [344] = 1,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [356] = 6,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(120), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(13), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [378] = 1,
    ACTIONS(122), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [390] = 7,
    ACTIONS(124), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(126), 1,
      aux_sym_word_token1,
    ACTIONS(128), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(130), 1,
      sym__space,
    STATE(41), 1,
      sym_probability,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(39), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [414] = 1,
    ACTIONS(132), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [426] = 6,
    ACTIONS(50), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(52), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(54), 1,
      aux_sym_word_token1,
    ACTIONS(134), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(14), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [448] = 1,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [460] = 1,
    ACTIONS(138), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [471] = 1,
    ACTIONS(140), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [482] = 1,
    ACTIONS(142), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [493] = 1,
    ACTIONS(144), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [504] = 6,
    ACTIONS(124), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(126), 1,
      aux_sym_word_token1,
    ACTIONS(146), 1,
      sym__eol,
    ACTIONS(148), 1,
      sym__space,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(31), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [525] = 1,
    ACTIONS(150), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [536] = 1,
    ACTIONS(152), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [547] = 6,
    ACTIONS(154), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(157), 1,
      aux_sym_word_token1,
    ACTIONS(160), 1,
      sym__eol,
    ACTIONS(162), 1,
      sym__space,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(31), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [568] = 1,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [579] = 1,
    ACTIONS(167), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [590] = 1,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [601] = 1,
    ACTIONS(171), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [612] = 1,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [623] = 1,
    ACTIONS(175), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [634] = 1,
    ACTIONS(177), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [645] = 6,
    ACTIONS(124), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(126), 1,
      aux_sym_word_token1,
    ACTIONS(148), 1,
      sym__space,
    ACTIONS(179), 1,
      sym__eol,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(31), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [666] = 1,
    ACTIONS(181), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      anon_sym_PIPE,
      aux_sym_comment_token1,
      sym__eol,
  [677] = 5,
    ACTIONS(124), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(126), 1,
      aux_sym_word_token1,
    ACTIONS(183), 1,
      sym__space,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(28), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [695] = 3,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    STATE(43), 1,
      aux_sym_word_repeat1,
    ACTIONS(185), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [708] = 3,
    ACTIONS(191), 1,
      aux_sym_word_token1,
    STATE(43), 1,
      aux_sym_word_repeat1,
    ACTIONS(189), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [721] = 2,
    ACTIONS(196), 1,
      aux_sym_word_token1,
    ACTIONS(194), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [731] = 2,
    ACTIONS(200), 1,
      aux_sym_word_token1,
    ACTIONS(198), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [741] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(48), 1,
      sym__indent,
    STATE(26), 1,
      sym_intent_body,
    STATE(4), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [755] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(62), 1,
      sym__indent,
    STATE(24), 1,
      sym_alias_body,
    STATE(6), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [769] = 5,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    ACTIONS(206), 1,
      sym__space,
    STATE(104), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [785] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(62), 1,
      sym__indent,
    STATE(32), 1,
      sym_alias_body,
    STATE(6), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [799] = 2,
    ACTIONS(210), 1,
      aux_sym_word_token1,
    ACTIONS(208), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [809] = 2,
    ACTIONS(214), 1,
      aux_sym_word_token1,
    ACTIONS(212), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [819] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(48), 1,
      sym__indent,
    STATE(40), 1,
      sym_intent_body,
    STATE(4), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [833] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      sym__indent,
    STATE(38), 1,
      sym_slot_body,
    STATE(7), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [847] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      sym__indent,
    STATE(34), 1,
      sym_slot_body,
    STATE(7), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [861] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      sym__indent,
    STATE(35), 1,
      sym_slot_body,
    STATE(7), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [875] = 2,
    ACTIONS(218), 1,
      aux_sym_word_token1,
    ACTIONS(216), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [885] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(48), 1,
      sym__indent,
    STATE(36), 1,
      sym_intent_body,
    STATE(4), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [899] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(62), 1,
      sym__indent,
    STATE(27), 1,
      sym_alias_body,
    STATE(6), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [913] = 5,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    ACTIONS(220), 1,
      sym__space,
    STATE(78), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [929] = 3,
    ACTIONS(222), 1,
      aux_sym_word_token1,
    STATE(62), 1,
      aux_sym_word_repeat1,
    ACTIONS(185), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [941] = 5,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    ACTIONS(224), 1,
      sym__space,
    STATE(98), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [957] = 3,
    ACTIONS(226), 1,
      aux_sym_word_token1,
    STATE(62), 1,
      aux_sym_word_repeat1,
    ACTIONS(189), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [969] = 4,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      sym__indent,
    STATE(33), 1,
      sym_slot_body,
    STATE(7), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [983] = 4,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(231), 1,
      sym__eol,
    ACTIONS(233), 1,
      sym__space,
    STATE(125), 1,
      sym_arguments,
  [996] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(239), 1,
      sym__space,
    STATE(86), 1,
      aux_sym_arguments_repeat1,
  [1009] = 4,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(241), 1,
      sym__eol,
    ACTIONS(243), 1,
      sym__space,
    STATE(141), 1,
      sym_arguments,
  [1022] = 1,
    ACTIONS(245), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_eq,
      sym__space,
  [1029] = 4,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
    ACTIONS(249), 1,
      aux_sym_string_token1,
    ACTIONS(251), 1,
      sym_escape,
    STATE(90), 1,
      aux_sym_string_repeat1,
  [1042] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(239), 1,
      sym__space,
    STATE(75), 1,
      aux_sym_arguments_repeat1,
  [1055] = 4,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    ACTIONS(253), 1,
      sym__space,
    STATE(102), 1,
      sym_string,
  [1068] = 4,
    ACTIONS(247), 1,
      anon_sym_SQUOTE,
    ACTIONS(255), 1,
      aux_sym_string_token2,
    ACTIONS(257), 1,
      sym_escape,
    STATE(84), 1,
      aux_sym_string_repeat2,
  [1081] = 2,
    ACTIONS(214), 1,
      aux_sym_word_token1,
    ACTIONS(212), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1090] = 4,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    ACTIONS(261), 1,
      anon_sym_QMARK,
    ACTIONS(263), 1,
      anon_sym_POUND,
    STATE(113), 1,
      sym_variation,
  [1103] = 4,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    ACTIONS(265), 1,
      sym__space,
    STATE(93), 1,
      sym_string,
  [1116] = 4,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      sym__space,
    STATE(75), 1,
      aux_sym_arguments_repeat1,
  [1129] = 4,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(275), 1,
      sym__eol,
    ACTIONS(277), 1,
      sym__space,
    STATE(143), 1,
      sym_arguments,
  [1142] = 4,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    STATE(99), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [1155] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      sym__space,
    STATE(69), 1,
      aux_sym_arguments_repeat1,
  [1168] = 4,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    STATE(65), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [1181] = 4,
    ACTIONS(283), 1,
      anon_sym_SQUOTE,
    ACTIONS(285), 1,
      aux_sym_string_token2,
    ACTIONS(287), 1,
      sym_escape,
    STATE(71), 1,
      aux_sym_string_repeat2,
  [1194] = 4,
    ACTIONS(283), 1,
      anon_sym_DQUOTE,
    ACTIONS(289), 1,
      aux_sym_string_token1,
    ACTIONS(291), 1,
      sym_escape,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1207] = 2,
    ACTIONS(295), 1,
      aux_sym_word_token1,
    ACTIONS(293), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1216] = 4,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    STATE(104), 1,
      sym_argument,
    STATE(114), 1,
      sym_string,
  [1229] = 4,
    ACTIONS(297), 1,
      anon_sym_SQUOTE,
    ACTIONS(299), 1,
      aux_sym_string_token2,
    ACTIONS(302), 1,
      sym_escape,
    STATE(84), 1,
      aux_sym_string_repeat2,
  [1242] = 2,
    ACTIONS(307), 1,
      aux_sym_word_token1,
    ACTIONS(305), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1251] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    ACTIONS(311), 1,
      sym__space,
    STATE(75), 1,
      aux_sym_arguments_repeat1,
  [1264] = 4,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(313), 1,
      sym__eol,
    ACTIONS(315), 1,
      sym__space,
    STATE(131), 1,
      sym_arguments,
  [1277] = 2,
    ACTIONS(196), 1,
      aux_sym_word_token1,
    ACTIONS(194), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1286] = 1,
    ACTIONS(317), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_eq,
      sym__space,
  [1293] = 4,
    ACTIONS(319), 1,
      anon_sym_DQUOTE,
    ACTIONS(321), 1,
      aux_sym_string_token1,
    ACTIONS(324), 1,
      sym_escape,
    STATE(90), 1,
      aux_sym_string_repeat1,
  [1306] = 3,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(327), 1,
      sym__eol,
    STATE(149), 1,
      sym_arguments,
  [1316] = 3,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(231), 1,
      sym__eol,
    STATE(125), 1,
      sym_arguments,
  [1326] = 1,
    ACTIONS(329), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1332] = 3,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    STATE(100), 1,
      sym_string,
  [1342] = 3,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(331), 1,
      sym__eol,
    STATE(126), 1,
      sym_arguments,
  [1352] = 2,
    ACTIONS(307), 1,
      aux_sym_word_token1,
    ACTIONS(305), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1360] = 2,
    ACTIONS(295), 1,
      aux_sym_word_token1,
    ACTIONS(293), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1368] = 1,
    ACTIONS(270), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1374] = 1,
    ACTIONS(333), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1380] = 1,
    ACTIONS(335), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1386] = 3,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
    STATE(93), 1,
      sym_string,
  [1396] = 1,
    ACTIONS(337), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1402] = 3,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    ACTIONS(339), 1,
      sym__eol,
    STATE(122), 1,
      sym_arguments,
  [1412] = 1,
    ACTIONS(341), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1418] = 3,
    ACTIONS(263), 1,
      anon_sym_POUND,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    STATE(148), 1,
      sym_variation,
  [1428] = 2,
    ACTIONS(345), 1,
      anon_sym_RBRACK,
    ACTIONS(347), 1,
      anon_sym_PERCENT,
  [1435] = 1,
    ACTIONS(349), 2,
      anon_sym_RBRACK,
      anon_sym_QMARK,
  [1440] = 2,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
    ACTIONS(353), 1,
      anon_sym_QMARK,
  [1447] = 2,
    ACTIONS(355), 1,
      sym__eol,
    ACTIONS(357), 1,
      sym__space,
  [1454] = 2,
    ACTIONS(359), 1,
      sym__eol,
    ACTIONS(361), 1,
      sym__space,
  [1461] = 2,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    ACTIONS(363), 1,
      anon_sym_COMMA,
  [1468] = 2,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(363), 1,
      anon_sym_COMMA,
  [1475] = 2,
    ACTIONS(365), 1,
      anon_sym_RBRACK,
    ACTIONS(367), 1,
      anon_sym_QMARK,
  [1482] = 2,
    ACTIONS(369), 1,
      sym_eq,
    ACTIONS(371), 1,
      sym__space,
  [1489] = 2,
    ACTIONS(373), 1,
      anon_sym_RBRACK,
    ACTIONS(375), 1,
      anon_sym_QMARK,
  [1496] = 2,
    ACTIONS(377), 1,
      anon_sym_RBRACK,
    ACTIONS(379), 1,
      anon_sym_PERCENT,
  [1503] = 2,
    ACTIONS(381), 1,
      aux_sym_import_token1,
    ACTIONS(383), 1,
      sym__space,
  [1510] = 2,
    ACTIONS(363), 1,
      anon_sym_COMMA,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
  [1517] = 1,
    ACTIONS(387), 1,
      aux_sym_intent_def_token1,
  [1521] = 1,
    ACTIONS(389), 1,
      aux_sym_slot_def_token1,
  [1525] = 1,
    ACTIONS(391), 1,
      sym__eol,
  [1529] = 1,
    ACTIONS(393), 1,
      sym__eol,
  [1533] = 1,
    ACTIONS(363), 1,
      anon_sym_COMMA,
  [1537] = 1,
    ACTIONS(395), 1,
      anon_sym_RBRACK,
  [1541] = 1,
    ACTIONS(327), 1,
      sym__eol,
  [1545] = 1,
    ACTIONS(397), 1,
      sym__eol,
  [1549] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACK,
  [1553] = 1,
    ACTIONS(399), 1,
      sym__eol,
  [1557] = 1,
    ACTIONS(401), 1,
      sym__eol,
  [1561] = 1,
    ACTIONS(403), 1,
      anon_sym_RBRACK,
  [1565] = 1,
    ACTIONS(331), 1,
      sym__eol,
  [1569] = 1,
    ACTIONS(405), 1,
      anon_sym_RBRACK,
  [1573] = 1,
    ACTIONS(407), 1,
      aux_sym_intent_def_token1,
  [1577] = 1,
    ACTIONS(409), 1,
      aux_sym_slot_def_token1,
  [1581] = 1,
    ACTIONS(411), 1,
      sym__eol,
  [1585] = 1,
    ACTIONS(413), 1,
      sym__eol,
  [1589] = 1,
    ACTIONS(415), 1,
      sym_eq,
  [1593] = 1,
    ACTIONS(417), 1,
      sym__space,
  [1597] = 1,
    ACTIONS(419), 1,
      ts_builtin_sym_end,
  [1601] = 1,
    ACTIONS(421), 1,
      anon_sym_RBRACK,
  [1605] = 1,
    ACTIONS(231), 1,
      sym__eol,
  [1609] = 1,
    ACTIONS(423), 1,
      anon_sym_RBRACK,
  [1613] = 1,
    ACTIONS(339), 1,
      sym__eol,
  [1617] = 1,
    ACTIONS(425), 1,
      sym_number,
  [1621] = 1,
    ACTIONS(359), 1,
      sym__eol,
  [1625] = 1,
    ACTIONS(427), 1,
      aux_sym_intent_def_token1,
  [1629] = 1,
    ACTIONS(429), 1,
      aux_sym_import_token1,
  [1633] = 1,
    ACTIONS(431), 1,
      anon_sym_RBRACK,
  [1637] = 1,
    ACTIONS(433), 1,
      sym__eol,
  [1641] = 1,
    ACTIONS(435), 1,
      aux_sym_slot_def_token1,
  [1645] = 1,
    ACTIONS(437), 1,
      sym__eol,
  [1649] = 1,
    ACTIONS(439), 1,
      anon_sym_RBRACK,
  [1653] = 1,
    ACTIONS(441), 1,
      anon_sym_RBRACK,
  [1657] = 1,
    ACTIONS(443), 1,
      aux_sym_intent_def_token1,
  [1661] = 1,
    ACTIONS(445), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 92,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 180,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 220,
  [SMALL_STATE(12)] = 245,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 295,
  [SMALL_STATE(15)] = 320,
  [SMALL_STATE(16)] = 332,
  [SMALL_STATE(17)] = 344,
  [SMALL_STATE(18)] = 356,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 390,
  [SMALL_STATE(21)] = 414,
  [SMALL_STATE(22)] = 426,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 460,
  [SMALL_STATE(25)] = 471,
  [SMALL_STATE(26)] = 482,
  [SMALL_STATE(27)] = 493,
  [SMALL_STATE(28)] = 504,
  [SMALL_STATE(29)] = 525,
  [SMALL_STATE(30)] = 536,
  [SMALL_STATE(31)] = 547,
  [SMALL_STATE(32)] = 568,
  [SMALL_STATE(33)] = 579,
  [SMALL_STATE(34)] = 590,
  [SMALL_STATE(35)] = 601,
  [SMALL_STATE(36)] = 612,
  [SMALL_STATE(37)] = 623,
  [SMALL_STATE(38)] = 634,
  [SMALL_STATE(39)] = 645,
  [SMALL_STATE(40)] = 666,
  [SMALL_STATE(41)] = 677,
  [SMALL_STATE(42)] = 695,
  [SMALL_STATE(43)] = 708,
  [SMALL_STATE(44)] = 721,
  [SMALL_STATE(45)] = 731,
  [SMALL_STATE(46)] = 741,
  [SMALL_STATE(47)] = 755,
  [SMALL_STATE(48)] = 769,
  [SMALL_STATE(49)] = 785,
  [SMALL_STATE(50)] = 799,
  [SMALL_STATE(51)] = 809,
  [SMALL_STATE(52)] = 819,
  [SMALL_STATE(53)] = 833,
  [SMALL_STATE(54)] = 847,
  [SMALL_STATE(55)] = 861,
  [SMALL_STATE(56)] = 875,
  [SMALL_STATE(57)] = 885,
  [SMALL_STATE(58)] = 899,
  [SMALL_STATE(59)] = 913,
  [SMALL_STATE(60)] = 929,
  [SMALL_STATE(61)] = 941,
  [SMALL_STATE(62)] = 957,
  [SMALL_STATE(63)] = 969,
  [SMALL_STATE(64)] = 983,
  [SMALL_STATE(65)] = 996,
  [SMALL_STATE(66)] = 1009,
  [SMALL_STATE(67)] = 1022,
  [SMALL_STATE(68)] = 1029,
  [SMALL_STATE(69)] = 1042,
  [SMALL_STATE(70)] = 1055,
  [SMALL_STATE(71)] = 1068,
  [SMALL_STATE(72)] = 1081,
  [SMALL_STATE(73)] = 1090,
  [SMALL_STATE(74)] = 1103,
  [SMALL_STATE(75)] = 1116,
  [SMALL_STATE(76)] = 1129,
  [SMALL_STATE(77)] = 1142,
  [SMALL_STATE(78)] = 1155,
  [SMALL_STATE(79)] = 1168,
  [SMALL_STATE(80)] = 1181,
  [SMALL_STATE(81)] = 1194,
  [SMALL_STATE(82)] = 1207,
  [SMALL_STATE(83)] = 1216,
  [SMALL_STATE(84)] = 1229,
  [SMALL_STATE(85)] = 1242,
  [SMALL_STATE(86)] = 1251,
  [SMALL_STATE(87)] = 1264,
  [SMALL_STATE(88)] = 1277,
  [SMALL_STATE(89)] = 1286,
  [SMALL_STATE(90)] = 1293,
  [SMALL_STATE(91)] = 1306,
  [SMALL_STATE(92)] = 1316,
  [SMALL_STATE(93)] = 1326,
  [SMALL_STATE(94)] = 1332,
  [SMALL_STATE(95)] = 1342,
  [SMALL_STATE(96)] = 1352,
  [SMALL_STATE(97)] = 1360,
  [SMALL_STATE(98)] = 1368,
  [SMALL_STATE(99)] = 1374,
  [SMALL_STATE(100)] = 1380,
  [SMALL_STATE(101)] = 1386,
  [SMALL_STATE(102)] = 1396,
  [SMALL_STATE(103)] = 1402,
  [SMALL_STATE(104)] = 1412,
  [SMALL_STATE(105)] = 1418,
  [SMALL_STATE(106)] = 1428,
  [SMALL_STATE(107)] = 1435,
  [SMALL_STATE(108)] = 1440,
  [SMALL_STATE(109)] = 1447,
  [SMALL_STATE(110)] = 1454,
  [SMALL_STATE(111)] = 1461,
  [SMALL_STATE(112)] = 1468,
  [SMALL_STATE(113)] = 1475,
  [SMALL_STATE(114)] = 1482,
  [SMALL_STATE(115)] = 1489,
  [SMALL_STATE(116)] = 1496,
  [SMALL_STATE(117)] = 1503,
  [SMALL_STATE(118)] = 1510,
  [SMALL_STATE(119)] = 1517,
  [SMALL_STATE(120)] = 1521,
  [SMALL_STATE(121)] = 1525,
  [SMALL_STATE(122)] = 1529,
  [SMALL_STATE(123)] = 1533,
  [SMALL_STATE(124)] = 1537,
  [SMALL_STATE(125)] = 1541,
  [SMALL_STATE(126)] = 1545,
  [SMALL_STATE(127)] = 1549,
  [SMALL_STATE(128)] = 1553,
  [SMALL_STATE(129)] = 1557,
  [SMALL_STATE(130)] = 1561,
  [SMALL_STATE(131)] = 1565,
  [SMALL_STATE(132)] = 1569,
  [SMALL_STATE(133)] = 1573,
  [SMALL_STATE(134)] = 1577,
  [SMALL_STATE(135)] = 1581,
  [SMALL_STATE(136)] = 1585,
  [SMALL_STATE(137)] = 1589,
  [SMALL_STATE(138)] = 1593,
  [SMALL_STATE(139)] = 1597,
  [SMALL_STATE(140)] = 1601,
  [SMALL_STATE(141)] = 1605,
  [SMALL_STATE(142)] = 1609,
  [SMALL_STATE(143)] = 1613,
  [SMALL_STATE(144)] = 1617,
  [SMALL_STATE(145)] = 1621,
  [SMALL_STATE(146)] = 1625,
  [SMALL_STATE(147)] = 1629,
  [SMALL_STATE(148)] = 1633,
  [SMALL_STATE(149)] = 1637,
  [SMALL_STATE(150)] = 1641,
  [SMALL_STATE(151)] = 1645,
  [SMALL_STATE(152)] = 1649,
  [SMALL_STATE(153)] = 1653,
  [SMALL_STATE(154)] = 1657,
  [SMALL_STATE(155)] = 1661,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(146),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(134),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(133),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(138),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(117),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(135),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_body, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_body, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_body, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2), SHIFT_REPEAT(135),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2), SHIFT_REPEAT(22),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2), SHIFT_REPEAT(135),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2), SHIFT_REPEAT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2), SHIFT_REPEAT(135),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2), SHIFT_REPEAT(5),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(120),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(119),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(42),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 7),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 7, .production_id = 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 6),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(154),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(60),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(31),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 5),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 7, .production_id = 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 5, .production_id = 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 6, .production_id = 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 5, .production_id = 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 8, .production_id = 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 6, .production_id = 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(43),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 3),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 3, .production_id = 3),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 3, .production_id = 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 4, .production_id = 3),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 4, .production_id = 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 4),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 5, .production_id = 3),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 5, .production_id = 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [226] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(62),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, .production_id = 4),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(61),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(123),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 3),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 3),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [299] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(84),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(84),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 4),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 4),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 5),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [321] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(90),
  [324] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(90),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 4, .production_id = 7),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 4),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 5, .production_id = 8),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 6),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 3),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variation, 2, .production_id = 1),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [413] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 6),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [419] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [437] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chatette(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
