#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 153
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 2
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 10

enum {
  anon_sym_PERCENT_LBRACK = 1,
  aux_sym_intent_def_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_AT_LBRACK = 4,
  aux_sym_slot_def_token1 = 5,
  anon_sym_TILDE_LBRACK = 6,
  anon_sym_import = 7,
  aux_sym_import_token1 = 8,
  aux_sym_comment_token1 = 9,
  anon_sym_QMARK = 10,
  aux_sym_word_token1 = 11,
  anon_sym_POUND = 12,
  anon_sym_STAR_LBRACK = 13,
  anon_sym_PERCENT = 14,
  sym_number = 15,
  anon_sym_LPAREN = 16,
  anon_sym_COMMA = 17,
  anon_sym_RPAREN = 18,
  sym_eq = 19,
  anon_sym_BQUOTE = 20,
  aux_sym_string_token1 = 21,
  sym_escape = 22,
  sym__eol = 23,
  sym__indent = 24,
  sym__space = 25,
  sym_source = 26,
  sym__definition = 27,
  sym_intent_def = 28,
  sym_slot_def = 29,
  sym_alias_def = 30,
  sym_import = 31,
  sym_comment = 32,
  sym_intent_body = 33,
  sym_slot_body = 34,
  sym_alias_body = 35,
  sym_slot_ref = 36,
  sym_alias_ref = 37,
  sym_word = 38,
  sym_variation = 39,
  sym_probability = 40,
  sym_arguments = 41,
  sym_argument = 42,
  sym_string = 43,
  aux_sym_source_repeat1 = 44,
  aux_sym_intent_body_repeat1 = 45,
  aux_sym_intent_body_repeat2 = 46,
  aux_sym_slot_body_repeat1 = 47,
  aux_sym_slot_body_repeat2 = 48,
  aux_sym_alias_body_repeat1 = 49,
  aux_sym_word_repeat1 = 50,
  aux_sym_arguments_repeat1 = 51,
  aux_sym_string_repeat1 = 52,
  alias_sym_intent = 53,
  alias_sym_slot = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT_LBRACK] = "%[",
  [aux_sym_intent_def_token1] = "alias",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT_LBRACK] = "@[",
  [aux_sym_slot_def_token1] = "slot_def_token1",
  [anon_sym_TILDE_LBRACK] = "~[",
  [anon_sym_import] = "import",
  [aux_sym_import_token1] = "file",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_QMARK] = "\?",
  [aux_sym_word_token1] = "word_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_STAR_LBRACK] = "*[",
  [anon_sym_PERCENT] = "%",
  [sym_number] = "number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_eq] = "eq",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape] = "escape",
  [sym__eol] = "_eol",
  [sym__indent] = "_indent",
  [sym__space] = "_space",
  [sym_source] = "source",
  [sym__definition] = "_definition",
  [sym_intent_def] = "intent_def",
  [sym_slot_def] = "slot_def",
  [sym_alias_def] = "alias_def",
  [sym_import] = "import",
  [sym_comment] = "comment",
  [sym_intent_body] = "intent_body",
  [sym_slot_body] = "slot_body",
  [sym_alias_body] = "alias_body",
  [sym_slot_ref] = "slot_ref",
  [sym_alias_ref] = "alias_ref",
  [sym_word] = "word",
  [sym_variation] = "variation",
  [sym_probability] = "probability",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_string] = "string",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_intent_body_repeat1] = "intent_body_repeat1",
  [aux_sym_intent_body_repeat2] = "intent_body_repeat2",
  [aux_sym_slot_body_repeat1] = "slot_body_repeat1",
  [aux_sym_slot_body_repeat2] = "slot_body_repeat2",
  [aux_sym_alias_body_repeat1] = "alias_body_repeat1",
  [aux_sym_word_repeat1] = "word_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_intent] = "intent",
  [alias_sym_slot] = "slot",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT_LBRACK] = anon_sym_PERCENT_LBRACK,
  [aux_sym_intent_def_token1] = aux_sym_intent_def_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [aux_sym_slot_def_token1] = aux_sym_slot_def_token1,
  [anon_sym_TILDE_LBRACK] = anon_sym_TILDE_LBRACK,
  [anon_sym_import] = anon_sym_import,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_STAR_LBRACK] = anon_sym_STAR_LBRACK,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_number] = sym_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_eq] = sym_eq,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape] = sym_escape,
  [sym__eol] = sym__eol,
  [sym__indent] = sym__indent,
  [sym__space] = sym__space,
  [sym_source] = sym_source,
  [sym__definition] = sym__definition,
  [sym_intent_def] = sym_intent_def,
  [sym_slot_def] = sym_slot_def,
  [sym_alias_def] = sym_alias_def,
  [sym_import] = sym_import,
  [sym_comment] = sym_comment,
  [sym_intent_body] = sym_intent_body,
  [sym_slot_body] = sym_slot_body,
  [sym_alias_body] = sym_alias_body,
  [sym_slot_ref] = sym_slot_ref,
  [sym_alias_ref] = sym_alias_ref,
  [sym_word] = sym_word,
  [sym_variation] = sym_variation,
  [sym_probability] = sym_probability,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym_string] = sym_string,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_intent_body_repeat1] = aux_sym_intent_body_repeat1,
  [aux_sym_intent_body_repeat2] = aux_sym_intent_body_repeat2,
  [aux_sym_slot_body_repeat1] = aux_sym_slot_body_repeat1,
  [aux_sym_slot_body_repeat2] = aux_sym_slot_body_repeat2,
  [aux_sym_alias_body_repeat1] = aux_sym_alias_body_repeat1,
  [aux_sym_word_repeat1] = aux_sym_word_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_intent] = alias_sym_intent,
  [alias_sym_slot] = alias_sym_slot,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_intent_def_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_slot_def_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_intent_def] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_def] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_def] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_intent_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_body] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_body] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_variation] = {
    .visible = true,
    .named = true,
  },
  [sym_probability] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_intent_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slot_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_alias_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_intent] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_slot] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_content = 1,
  field_id = 2,
  field_key = 3,
  field_quote = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_key] = "key",
  [field_quote] = "quote",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [5] = {.index = 2, .length = 2},
  [6] = {.index = 4, .length = 3},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_content, 0},
  [2] =
    {field_quote, 0},
    {field_quote, 1},
  [4] =
    {field_content, 1},
    {field_quote, 0},
    {field_quote, 2},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_key, 0},
    {field_value, 3},
  [11] =
    {field_key, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [1] = alias_sym_intent,
  },
  [4] = {
    [1] = alias_sym_slot,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 41,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 42,
  [69] = 41,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 52,
  [74] = 74,
  [75] = 41,
  [76] = 53,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 60,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 90,
  [101] = 101,
  [102] = 78,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 109,
  [114] = 114,
  [115] = 115,
  [116] = 108,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 124,
  [150] = 126,
  [151] = 148,
  [152] = 144,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      if (lookahead == '\t') ADVANCE(58);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(58);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '%') ADVANCE(49);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '?') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '`') ADVANCE(57);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '%') ADVANCE(49);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '?') ADVANCE(42);
      if (lookahead == ']') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '@') ADVANCE(44);
      if (lookahead == '~') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '@') ADVANCE(44);
      if (lookahead == '~') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '~') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '~') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '`') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == '[') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '`') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(58);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(27);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          ('t' <= lookahead && lookahead <= 'v')) ADVANCE(59);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '\t') ADVANCE(61);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '0') ADVANCE(50);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '?') ADVANCE(42);
      if (lookahead == '@') ADVANCE(14);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == '~') ADVANCE(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_intent_def_token1);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_slot_def_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '?' &&
          lookahead != ']') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_TILDE_LBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_import_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_word_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(36);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(38);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '[') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR_LBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(23);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__indent);
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 31},
  [2] = {.lex_state = 31},
  [3] = {.lex_state = 31},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 31},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 31},
  [11] = {.lex_state = 31},
  [12] = {.lex_state = 31},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 31},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 31},
  [22] = {.lex_state = 31},
  [23] = {.lex_state = 31},
  [24] = {.lex_state = 31},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 31},
  [28] = {.lex_state = 31},
  [29] = {.lex_state = 31},
  [30] = {.lex_state = 31},
  [31] = {.lex_state = 31},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 31},
  [34] = {.lex_state = 31},
  [35] = {.lex_state = 31},
  [36] = {.lex_state = 31},
  [37] = {.lex_state = 31},
  [38] = {.lex_state = 31},
  [39] = {.lex_state = 31},
  [40] = {.lex_state = 31},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 31},
  [49] = {.lex_state = 31},
  [50] = {.lex_state = 31},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 31},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 31},
  [58] = {.lex_state = 31},
  [59] = {.lex_state = 31},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 11},
  [62] = {.lex_state = 11},
  [63] = {.lex_state = 11},
  [64] = {.lex_state = 31},
  [65] = {.lex_state = 11},
  [66] = {.lex_state = 31},
  [67] = {.lex_state = 31},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 8},
  [72] = {.lex_state = 16},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 10},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 8},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 11},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 10},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 16},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 8},
  [92] = {.lex_state = 11},
  [93] = {.lex_state = 8},
  [94] = {.lex_state = 31},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 8},
  [97] = {.lex_state = 8},
  [98] = {.lex_state = 8},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 8},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 31},
  [104] = {.lex_state = 31},
  [105] = {.lex_state = 31},
  [106] = {.lex_state = 31},
  [107] = {.lex_state = 31},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 31},
  [110] = {.lex_state = 31},
  [111] = {.lex_state = 31},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 31},
  [114] = {.lex_state = 31},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 30},
  [118] = {.lex_state = 31},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 31},
  [121] = {.lex_state = 31},
  [122] = {.lex_state = 31},
  [123] = {.lex_state = 28},
  [124] = {.lex_state = 31},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 31},
  [127] = {.lex_state = 28},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 31},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 31},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 3},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 31},
  [143] = {.lex_state = 29},
  [144] = {.lex_state = 31},
  [145] = {.lex_state = 29},
  [146] = {.lex_state = 28},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 29},
  [149] = {.lex_state = 31},
  [150] = {.lex_state = 31},
  [151] = {.lex_state = 29},
  [152] = {.lex_state = 31},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [aux_sym_word_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(138),
    [sym__definition] = STATE(2),
    [sym_intent_def] = STATE(36),
    [sym_slot_def] = STATE(36),
    [sym_alias_def] = STATE(36),
    [sym_import] = STATE(2),
    [sym_comment] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT_LBRACK] = ACTIONS(5),
    [anon_sym_AT_LBRACK] = ACTIONS(7),
    [anon_sym_TILDE_LBRACK] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(13),
    [sym__eol] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(7), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(9), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__eol,
    STATE(36), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(3), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [33] = 9,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_PERCENT_LBRACK,
    ACTIONS(26), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(29), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(32), 1,
      anon_sym_import,
    ACTIONS(35), 1,
      aux_sym_comment_token1,
    ACTIONS(38), 1,
      sym__eol,
    STATE(36), 3,
      sym_intent_def,
      sym_slot_def,
      sym_alias_def,
    STATE(3), 4,
      sym__definition,
      sym_import,
      sym_comment,
      aux_sym_source_repeat1,
  [66] = 8,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(47), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(49), 1,
      sym__space,
    STATE(15), 1,
      sym_probability,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(6), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [94] = 7,
    ACTIONS(51), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(54), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(57), 1,
      aux_sym_word_token1,
    ACTIONS(60), 1,
      sym__eol,
    ACTIONS(62), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(5), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [119] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(65), 1,
      sym__eol,
    ACTIONS(67), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(5), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [144] = 4,
    ACTIONS(71), 1,
      aux_sym_comment_token1,
    ACTIONS(74), 1,
      sym__indent,
    STATE(7), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [163] = 4,
    ACTIONS(79), 1,
      aux_sym_comment_token1,
    ACTIONS(82), 1,
      sym__indent,
    STATE(8), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [182] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(67), 1,
      sym__space,
    ACTIONS(85), 1,
      sym__eol,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(5), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [207] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      sym__indent,
    STATE(11), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [226] = 4,
    ACTIONS(93), 1,
      aux_sym_comment_token1,
    ACTIONS(96), 1,
      sym__indent,
    STATE(11), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [245] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      sym__indent,
    STATE(8), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [264] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(105), 1,
      sym__indent,
    STATE(7), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      sym__eol,
  [283] = 7,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(67), 1,
      sym__space,
    ACTIONS(107), 1,
      sym__eol,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(5), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [308] = 6,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(109), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(14), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [330] = 6,
    ACTIONS(41), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(43), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(45), 1,
      aux_sym_word_token1,
    ACTIONS(111), 1,
      sym__space,
    STATE(42), 1,
      aux_sym_word_repeat1,
    STATE(9), 4,
      sym_slot_ref,
      sym_alias_ref,
      sym_word,
      aux_sym_intent_body_repeat1,
  [352] = 7,
    ACTIONS(113), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(115), 1,
      aux_sym_word_token1,
    ACTIONS(117), 1,
      anon_sym_STAR_LBRACK,
    ACTIONS(119), 1,
      sym__space,
    STATE(32), 1,
      sym_probability,
    STATE(68), 1,
      aux_sym_word_repeat1,
    STATE(20), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [376] = 1,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [387] = 1,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [398] = 6,
    ACTIONS(113), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(115), 1,
      aux_sym_word_token1,
    ACTIONS(125), 1,
      sym__eol,
    ACTIONS(127), 1,
      sym__space,
    STATE(68), 1,
      aux_sym_word_repeat1,
    STATE(26), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [419] = 1,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [430] = 1,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [441] = 1,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [452] = 1,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
      sym__indent,
  [463] = 6,
    ACTIONS(113), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(115), 1,
      aux_sym_word_token1,
    ACTIONS(127), 1,
      sym__space,
    ACTIONS(137), 1,
      sym__eol,
    STATE(68), 1,
      aux_sym_word_repeat1,
    STATE(26), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [484] = 6,
    ACTIONS(139), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(142), 1,
      aux_sym_word_token1,
    ACTIONS(145), 1,
      sym__eol,
    ACTIONS(147), 1,
      sym__space,
    STATE(68), 1,
      aux_sym_word_repeat1,
    STATE(26), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [505] = 1,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [515] = 1,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [525] = 1,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [535] = 1,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [545] = 1,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [555] = 5,
    ACTIONS(113), 1,
      anon_sym_TILDE_LBRACK,
    ACTIONS(115), 1,
      aux_sym_word_token1,
    ACTIONS(160), 1,
      sym__space,
    STATE(68), 1,
      aux_sym_word_repeat1,
    STATE(25), 3,
      sym_alias_ref,
      sym_word,
      aux_sym_slot_body_repeat1,
  [573] = 1,
    ACTIONS(162), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [583] = 1,
    ACTIONS(164), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [593] = 1,
    ACTIONS(166), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [603] = 1,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [613] = 1,
    ACTIONS(170), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [623] = 1,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [633] = 1,
    ACTIONS(174), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [643] = 1,
    ACTIONS(176), 7,
      ts_builtin_sym_end,
      anon_sym_PERCENT_LBRACK,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      anon_sym_import,
      aux_sym_comment_token1,
      sym__eol,
  [653] = 3,
    ACTIONS(180), 1,
      aux_sym_word_token1,
    STATE(41), 1,
      aux_sym_word_repeat1,
    ACTIONS(178), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [666] = 3,
    ACTIONS(185), 1,
      aux_sym_word_token1,
    STATE(41), 1,
      aux_sym_word_repeat1,
    ACTIONS(183), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [679] = 6,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(191), 1,
      sym__space,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(93), 1,
      sym_argument,
    STATE(115), 1,
      sym_string,
  [698] = 6,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(193), 1,
      sym__space,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(101), 1,
      sym_argument,
    STATE(115), 1,
      sym_string,
  [717] = 6,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(195), 1,
      sym__space,
    STATE(70), 1,
      sym_argument,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(115), 1,
      sym_string,
  [736] = 3,
    ACTIONS(197), 1,
      aux_sym_word_token1,
    STATE(46), 1,
      aux_sym_word_repeat1,
    ACTIONS(178), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [748] = 5,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(101), 1,
      sym_argument,
    STATE(115), 1,
      sym_string,
  [764] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      sym__indent,
    STATE(39), 1,
      sym_slot_body,
    STATE(12), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [778] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      sym__indent,
    STATE(34), 1,
      sym_slot_body,
    STATE(12), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [792] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(105), 1,
      sym__indent,
    STATE(30), 1,
      sym_intent_body,
    STATE(13), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [806] = 2,
    ACTIONS(202), 1,
      aux_sym_word_token1,
    ACTIONS(200), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [816] = 2,
    ACTIONS(206), 1,
      aux_sym_word_token1,
    ACTIONS(204), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [826] = 2,
    ACTIONS(210), 1,
      aux_sym_word_token1,
    ACTIONS(208), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [836] = 2,
    ACTIONS(214), 1,
      aux_sym_word_token1,
    ACTIONS(212), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [846] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      sym__indent,
    STATE(38), 1,
      sym_alias_body,
    STATE(10), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [860] = 2,
    ACTIONS(218), 1,
      aux_sym_word_token1,
    ACTIONS(216), 4,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [870] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      sym__indent,
    STATE(28), 1,
      sym_alias_body,
    STATE(10), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [884] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      sym__indent,
    STATE(29), 1,
      sym_slot_body,
    STATE(12), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [898] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(105), 1,
      sym__indent,
    STATE(27), 1,
      sym_intent_body,
    STATE(13), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [912] = 3,
    ACTIONS(220), 1,
      aux_sym_word_token1,
    STATE(46), 1,
      aux_sym_word_repeat1,
    ACTIONS(222), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [924] = 5,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    STATE(80), 1,
      sym_argument,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(115), 1,
      sym_string,
  [940] = 5,
    ACTIONS(187), 1,
      aux_sym_word_token1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    STATE(85), 1,
      aux_sym_word_repeat1,
    STATE(95), 1,
      sym_argument,
    STATE(115), 1,
      sym_string,
  [956] = 5,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(224), 1,
      aux_sym_word_token1,
    ACTIONS(226), 1,
      sym__space,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(98), 1,
      sym_string,
  [972] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(105), 1,
      sym__indent,
    STATE(31), 1,
      sym_intent_body,
    STATE(13), 2,
      sym_comment,
      aux_sym_intent_body_repeat2,
  [986] = 5,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(224), 1,
      aux_sym_word_token1,
    ACTIONS(228), 1,
      sym__space,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(97), 1,
      sym_string,
  [1002] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      sym__indent,
    STATE(37), 1,
      sym_alias_body,
    STATE(10), 2,
      sym_comment,
      aux_sym_alias_body_repeat1,
  [1016] = 4,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      sym__indent,
    STATE(40), 1,
      sym_slot_body,
    STATE(12), 2,
      sym_comment,
      aux_sym_slot_body_repeat2,
  [1030] = 3,
    ACTIONS(230), 1,
      aux_sym_word_token1,
    STATE(69), 1,
      aux_sym_word_repeat1,
    ACTIONS(183), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1042] = 3,
    ACTIONS(232), 1,
      aux_sym_word_token1,
    STATE(69), 1,
      aux_sym_word_repeat1,
    ACTIONS(178), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1054] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(239), 1,
      sym__space,
    STATE(77), 1,
      aux_sym_arguments_repeat1,
  [1067] = 4,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    ACTIONS(246), 1,
      sym__space,
    STATE(71), 1,
      aux_sym_arguments_repeat1,
  [1080] = 3,
    ACTIONS(249), 1,
      anon_sym_BQUOTE,
    STATE(81), 1,
      aux_sym_string_repeat1,
    ACTIONS(251), 2,
      aux_sym_string_token1,
      sym_escape,
  [1091] = 2,
    ACTIONS(206), 1,
      aux_sym_word_token1,
    ACTIONS(204), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1100] = 4,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(255), 1,
      sym__eol,
    ACTIONS(257), 1,
      sym__space,
    STATE(141), 1,
      sym_arguments,
  [1113] = 3,
    ACTIONS(259), 1,
      aux_sym_word_token1,
    STATE(75), 1,
      aux_sym_word_repeat1,
    ACTIONS(178), 2,
      sym_eq,
      sym__space,
  [1124] = 2,
    ACTIONS(210), 1,
      aux_sym_word_token1,
    ACTIONS(208), 3,
      anon_sym_TILDE_LBRACK,
      sym__eol,
      sym__space,
  [1133] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      sym__space,
    STATE(71), 1,
      aux_sym_arguments_repeat1,
  [1146] = 2,
    ACTIONS(268), 1,
      aux_sym_word_token1,
    ACTIONS(266), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1155] = 4,
    ACTIONS(270), 1,
      anon_sym_RBRACK,
    ACTIONS(272), 1,
      anon_sym_QMARK,
    ACTIONS(274), 1,
      anon_sym_POUND,
    STATE(107), 1,
      sym_variation,
  [1168] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      sym__space,
    STATE(91), 1,
      aux_sym_arguments_repeat1,
  [1181] = 3,
    ACTIONS(276), 1,
      anon_sym_BQUOTE,
    STATE(88), 1,
      aux_sym_string_repeat1,
    ACTIONS(278), 2,
      aux_sym_string_token1,
      sym_escape,
  [1192] = 4,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(224), 1,
      aux_sym_word_token1,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(98), 1,
      sym_string,
  [1205] = 1,
    ACTIONS(280), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_eq,
      sym__space,
  [1212] = 4,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(282), 1,
      sym__eol,
    ACTIONS(284), 1,
      sym__space,
    STATE(131), 1,
      sym_arguments,
  [1225] = 3,
    ACTIONS(286), 1,
      aux_sym_word_token1,
    STATE(75), 1,
      aux_sym_word_repeat1,
    ACTIONS(222), 2,
      sym_eq,
      sym__space,
  [1236] = 4,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(288), 1,
      sym__eol,
    ACTIONS(290), 1,
      sym__space,
    STATE(147), 1,
      sym_arguments,
  [1249] = 1,
    ACTIONS(292), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_eq,
      sym__space,
  [1256] = 3,
    ACTIONS(294), 1,
      anon_sym_BQUOTE,
    STATE(88), 1,
      aux_sym_string_repeat1,
    ACTIONS(296), 2,
      aux_sym_string_token1,
      sym_escape,
  [1267] = 4,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(299), 1,
      sym__eol,
    ACTIONS(301), 1,
      sym__space,
    STATE(129), 1,
      sym_arguments,
  [1280] = 2,
    ACTIONS(305), 1,
      aux_sym_word_token1,
    ACTIONS(303), 3,
      anon_sym_AT_LBRACK,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1289] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    ACTIONS(309), 1,
      sym__space,
    STATE(71), 1,
      aux_sym_arguments_repeat1,
  [1302] = 4,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
    ACTIONS(224), 1,
      aux_sym_word_token1,
    STATE(60), 1,
      aux_sym_word_repeat1,
    STATE(96), 1,
      sym_string,
  [1315] = 1,
    ACTIONS(244), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1321] = 3,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(311), 1,
      sym__eol,
    STATE(135), 1,
      sym_arguments,
  [1331] = 1,
    ACTIONS(313), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1337] = 1,
    ACTIONS(315), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1343] = 1,
    ACTIONS(317), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1349] = 1,
    ACTIONS(319), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1355] = 3,
    ACTIONS(274), 1,
      anon_sym_POUND,
    ACTIONS(321), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      sym_variation,
  [1365] = 2,
    ACTIONS(305), 1,
      aux_sym_word_token1,
    ACTIONS(303), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1373] = 1,
    ACTIONS(323), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__space,
  [1379] = 2,
    ACTIONS(268), 1,
      aux_sym_word_token1,
    ACTIONS(266), 2,
      anon_sym_TILDE_LBRACK,
      sym__space,
  [1387] = 3,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(325), 1,
      sym__eol,
    STATE(125), 1,
      sym_arguments,
  [1397] = 3,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(282), 1,
      sym__eol,
    STATE(131), 1,
      sym_arguments,
  [1407] = 3,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    ACTIONS(327), 1,
      sym__eol,
    STATE(132), 1,
      sym_arguments,
  [1417] = 2,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    ACTIONS(329), 1,
      anon_sym_COMMA,
  [1424] = 2,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
    ACTIONS(333), 1,
      anon_sym_QMARK,
  [1431] = 2,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    ACTIONS(337), 1,
      anon_sym_PERCENT,
  [1438] = 2,
    ACTIONS(339), 1,
      anon_sym_RBRACK,
    ACTIONS(341), 1,
      anon_sym_QMARK,
  [1445] = 2,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(329), 1,
      anon_sym_COMMA,
  [1452] = 1,
    ACTIONS(343), 2,
      anon_sym_RBRACK,
      anon_sym_QMARK,
  [1457] = 2,
    ACTIONS(345), 1,
      sym__eol,
    ACTIONS(347), 1,
      sym__space,
  [1464] = 2,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
    ACTIONS(351), 1,
      anon_sym_QMARK,
  [1471] = 2,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(353), 1,
      anon_sym_RPAREN,
  [1478] = 2,
    ACTIONS(355), 1,
      sym_eq,
    ACTIONS(357), 1,
      sym__space,
  [1485] = 2,
    ACTIONS(359), 1,
      anon_sym_RBRACK,
    ACTIONS(361), 1,
      anon_sym_PERCENT,
  [1492] = 1,
    ACTIONS(363), 1,
      aux_sym_import_token1,
  [1496] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACK,
  [1500] = 1,
    ACTIONS(367), 1,
      sym__eol,
  [1504] = 1,
    ACTIONS(329), 1,
      anon_sym_COMMA,
  [1508] = 1,
    ACTIONS(369), 1,
      anon_sym_RBRACK,
  [1512] = 1,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
  [1516] = 1,
    ACTIONS(371), 1,
      aux_sym_slot_def_token1,
  [1520] = 1,
    ACTIONS(373), 1,
      anon_sym_RBRACK,
  [1524] = 1,
    ACTIONS(375), 1,
      sym__eol,
  [1528] = 1,
    ACTIONS(377), 1,
      anon_sym_RBRACK,
  [1532] = 1,
    ACTIONS(379), 1,
      aux_sym_slot_def_token1,
  [1536] = 1,
    ACTIONS(381), 1,
      sym__eol,
  [1540] = 1,
    ACTIONS(282), 1,
      sym__eol,
  [1544] = 1,
    ACTIONS(383), 1,
      sym__eol,
  [1548] = 1,
    ACTIONS(311), 1,
      sym__eol,
  [1552] = 1,
    ACTIONS(385), 1,
      sym__eol,
  [1556] = 1,
    ACTIONS(387), 1,
      anon_sym_RBRACK,
  [1560] = 1,
    ACTIONS(389), 1,
      sym__eol,
  [1564] = 1,
    ACTIONS(391), 1,
      sym__eol,
  [1568] = 1,
    ACTIONS(393), 1,
      sym__eol,
  [1572] = 1,
    ACTIONS(395), 1,
      anon_sym_RBRACK,
  [1576] = 1,
    ACTIONS(397), 1,
      ts_builtin_sym_end,
  [1580] = 1,
    ACTIONS(399), 1,
      sym__eol,
  [1584] = 1,
    ACTIONS(401), 1,
      sym__space,
  [1588] = 1,
    ACTIONS(327), 1,
      sym__eol,
  [1592] = 1,
    ACTIONS(403), 1,
      sym_eq,
  [1596] = 1,
    ACTIONS(405), 1,
      aux_sym_intent_def_token1,
  [1600] = 1,
    ACTIONS(407), 1,
      sym_number,
  [1604] = 1,
    ACTIONS(409), 1,
      aux_sym_intent_def_token1,
  [1608] = 1,
    ACTIONS(411), 1,
      aux_sym_slot_def_token1,
  [1612] = 1,
    ACTIONS(325), 1,
      sym__eol,
  [1616] = 1,
    ACTIONS(413), 1,
      aux_sym_intent_def_token1,
  [1620] = 1,
    ACTIONS(415), 1,
      anon_sym_RBRACK,
  [1624] = 1,
    ACTIONS(417), 1,
      anon_sym_RBRACK,
  [1628] = 1,
    ACTIONS(419), 1,
      aux_sym_intent_def_token1,
  [1632] = 1,
    ACTIONS(421), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 163,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 207,
  [SMALL_STATE(11)] = 226,
  [SMALL_STATE(12)] = 245,
  [SMALL_STATE(13)] = 264,
  [SMALL_STATE(14)] = 283,
  [SMALL_STATE(15)] = 308,
  [SMALL_STATE(16)] = 330,
  [SMALL_STATE(17)] = 352,
  [SMALL_STATE(18)] = 376,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 398,
  [SMALL_STATE(21)] = 419,
  [SMALL_STATE(22)] = 430,
  [SMALL_STATE(23)] = 441,
  [SMALL_STATE(24)] = 452,
  [SMALL_STATE(25)] = 463,
  [SMALL_STATE(26)] = 484,
  [SMALL_STATE(27)] = 505,
  [SMALL_STATE(28)] = 515,
  [SMALL_STATE(29)] = 525,
  [SMALL_STATE(30)] = 535,
  [SMALL_STATE(31)] = 545,
  [SMALL_STATE(32)] = 555,
  [SMALL_STATE(33)] = 573,
  [SMALL_STATE(34)] = 583,
  [SMALL_STATE(35)] = 593,
  [SMALL_STATE(36)] = 603,
  [SMALL_STATE(37)] = 613,
  [SMALL_STATE(38)] = 623,
  [SMALL_STATE(39)] = 633,
  [SMALL_STATE(40)] = 643,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 666,
  [SMALL_STATE(43)] = 679,
  [SMALL_STATE(44)] = 698,
  [SMALL_STATE(45)] = 717,
  [SMALL_STATE(46)] = 736,
  [SMALL_STATE(47)] = 748,
  [SMALL_STATE(48)] = 764,
  [SMALL_STATE(49)] = 778,
  [SMALL_STATE(50)] = 792,
  [SMALL_STATE(51)] = 806,
  [SMALL_STATE(52)] = 816,
  [SMALL_STATE(53)] = 826,
  [SMALL_STATE(54)] = 836,
  [SMALL_STATE(55)] = 846,
  [SMALL_STATE(56)] = 860,
  [SMALL_STATE(57)] = 870,
  [SMALL_STATE(58)] = 884,
  [SMALL_STATE(59)] = 898,
  [SMALL_STATE(60)] = 912,
  [SMALL_STATE(61)] = 924,
  [SMALL_STATE(62)] = 940,
  [SMALL_STATE(63)] = 956,
  [SMALL_STATE(64)] = 972,
  [SMALL_STATE(65)] = 986,
  [SMALL_STATE(66)] = 1002,
  [SMALL_STATE(67)] = 1016,
  [SMALL_STATE(68)] = 1030,
  [SMALL_STATE(69)] = 1042,
  [SMALL_STATE(70)] = 1054,
  [SMALL_STATE(71)] = 1067,
  [SMALL_STATE(72)] = 1080,
  [SMALL_STATE(73)] = 1091,
  [SMALL_STATE(74)] = 1100,
  [SMALL_STATE(75)] = 1113,
  [SMALL_STATE(76)] = 1124,
  [SMALL_STATE(77)] = 1133,
  [SMALL_STATE(78)] = 1146,
  [SMALL_STATE(79)] = 1155,
  [SMALL_STATE(80)] = 1168,
  [SMALL_STATE(81)] = 1181,
  [SMALL_STATE(82)] = 1192,
  [SMALL_STATE(83)] = 1205,
  [SMALL_STATE(84)] = 1212,
  [SMALL_STATE(85)] = 1225,
  [SMALL_STATE(86)] = 1236,
  [SMALL_STATE(87)] = 1249,
  [SMALL_STATE(88)] = 1256,
  [SMALL_STATE(89)] = 1267,
  [SMALL_STATE(90)] = 1280,
  [SMALL_STATE(91)] = 1289,
  [SMALL_STATE(92)] = 1302,
  [SMALL_STATE(93)] = 1315,
  [SMALL_STATE(94)] = 1321,
  [SMALL_STATE(95)] = 1331,
  [SMALL_STATE(96)] = 1337,
  [SMALL_STATE(97)] = 1343,
  [SMALL_STATE(98)] = 1349,
  [SMALL_STATE(99)] = 1355,
  [SMALL_STATE(100)] = 1365,
  [SMALL_STATE(101)] = 1373,
  [SMALL_STATE(102)] = 1379,
  [SMALL_STATE(103)] = 1387,
  [SMALL_STATE(104)] = 1397,
  [SMALL_STATE(105)] = 1407,
  [SMALL_STATE(106)] = 1417,
  [SMALL_STATE(107)] = 1424,
  [SMALL_STATE(108)] = 1431,
  [SMALL_STATE(109)] = 1438,
  [SMALL_STATE(110)] = 1445,
  [SMALL_STATE(111)] = 1452,
  [SMALL_STATE(112)] = 1457,
  [SMALL_STATE(113)] = 1464,
  [SMALL_STATE(114)] = 1471,
  [SMALL_STATE(115)] = 1478,
  [SMALL_STATE(116)] = 1485,
  [SMALL_STATE(117)] = 1492,
  [SMALL_STATE(118)] = 1496,
  [SMALL_STATE(119)] = 1500,
  [SMALL_STATE(120)] = 1504,
  [SMALL_STATE(121)] = 1508,
  [SMALL_STATE(122)] = 1512,
  [SMALL_STATE(123)] = 1516,
  [SMALL_STATE(124)] = 1520,
  [SMALL_STATE(125)] = 1524,
  [SMALL_STATE(126)] = 1528,
  [SMALL_STATE(127)] = 1532,
  [SMALL_STATE(128)] = 1536,
  [SMALL_STATE(129)] = 1540,
  [SMALL_STATE(130)] = 1544,
  [SMALL_STATE(131)] = 1548,
  [SMALL_STATE(132)] = 1552,
  [SMALL_STATE(133)] = 1556,
  [SMALL_STATE(134)] = 1560,
  [SMALL_STATE(135)] = 1564,
  [SMALL_STATE(136)] = 1568,
  [SMALL_STATE(137)] = 1572,
  [SMALL_STATE(138)] = 1576,
  [SMALL_STATE(139)] = 1580,
  [SMALL_STATE(140)] = 1584,
  [SMALL_STATE(141)] = 1588,
  [SMALL_STATE(142)] = 1592,
  [SMALL_STATE(143)] = 1596,
  [SMALL_STATE(144)] = 1600,
  [SMALL_STATE(145)] = 1604,
  [SMALL_STATE(146)] = 1608,
  [SMALL_STATE(147)] = 1612,
  [SMALL_STATE(148)] = 1616,
  [SMALL_STATE(149)] = 1620,
  [SMALL_STATE(150)] = 1624,
  [SMALL_STATE(151)] = 1628,
  [SMALL_STATE(152)] = 1632,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(143),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(146),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(145),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(140),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(139),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(127),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(148),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(42),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat1, 2), SHIFT_REPEAT(5),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2), SHIFT_REPEAT(139),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 2), SHIFT_REPEAT(4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2), SHIFT_REPEAT(139),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 2), SHIFT_REPEAT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_body, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2), SHIFT_REPEAT(139),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 2), SHIFT_REPEAT(16),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_body, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_body, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat2, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alias_body_repeat1, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_intent_body_repeat2, 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(151),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(68),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slot_body_repeat1, 2), SHIFT_REPEAT(26),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 5, .production_id = 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 7, .production_id = 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 6, .production_id = 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_def, 7, .production_id = 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 6, .production_id = 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 5),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_def, 6),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 8, .production_id = 4),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_def, 5, .production_id = 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(41),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [197] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(46),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 4, .production_id = 4),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 4, .production_id = 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 4),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 4),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 3),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 3, .production_id = 4),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 3, .production_id = 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_ref, 5, .production_id = 4),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_ref, 5, .production_id = 4),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, .production_id = 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [232] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(69),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(43),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(120),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [259] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_repeat1, 2), SHIFT_REPEAT(75),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 4),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 4),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, .production_id = 5),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, .production_id = 6),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(88),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_probability, 3),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_probability, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 4),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 5, .production_id = 9),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 7),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 4, .production_id = 8),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 3),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variation, 2, .production_id = 1),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 6),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [397] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chatl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
