name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
      - extensions/**
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
      - extensions/**

jobs:
  test:
    name: Test parsers
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Set up repository
        uses: tree-sitter/parser-setup-action@v1.1
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Clone examples
        uses: actions/checkout@v4
        with:
          path: examples/Chatito
          repository: rodrigopivi/Chatito
          sparse-checkout: examples
          ref: 25f95be775ad9729246422d99da0d8c7da43d3ba
      - name: Run tests
        uses: tree-sitter/parser-test-action@v1.2
        with:
          test-library: ${{runner.os == 'Linux'}}
          corpus-files: examples/Chatito/examples/
